export enum ActionTypesEnum {
    START_GAME = 'START_GAME',
    NEXT_QUESTION = 'NEXT_QUESTION',
    PREV_QUESTION = 'PREV_QUESTION',
    FINISH_GAME = 'FINISH_GAME',
    SET_ANSWER = 'SET_ANSWER',
    PLAY_AGAIN = 'PLAY_AGAIN',
    RESET_GAME = 'RESET_GAME'
}